### ISSUE TITLE
Target Price Input on iOS

### ISSUE THREAD

**Issue by lucafluri** [lucafluri/price_tracker#48]
iOS has no submit button on the number keyboard...

**Comment by AndiSwiss** [comment]
Possible solution: use  https://pub.dev/packages/keyboard_actions

Or see https://stackoverflow.com/questions/53505500/flutter-how-to-add-done-button-in-number-keyboard-in-flutter
Or https://blog.usejournal.com/keyboard-done-button-ux-in-flutter-ios-app-3b29ad46bacc

**Comment by AndiSwiss** [comment]
I worked a long time on it. https://pub.dev/packages/keyboard_actions seems to be quite useful, but then, because of the SingleChildScrollView and more, I always got render-flex errors. I was able to partly fix them, but then the done-button which appeared above the numbers, was hiding the actual number -> I was not able to fix that.

I consulted the following pages for problem solving (among others):
- https://blog.codemagic.io/flutter-tutorial-part-2
- https://stackoverflow.com/questions/52442724/boxconstraints-forces-an-infinite-width
- https://stackoverflow.com/questions/52645944/flutter-expanded-vs-flexible

The most simple and actually working solution is to just use the standard text-input -> also then, you have the decimal point and nothing is hiding the number.

Surely, this can be improved in the future; but this fix makes the app useable for now.
